### ISSUE TITLE
That's not super mario

### ISSUE THREAD

**Issue by Zhiyuan-Yang** [jsemu/gba#1]
That's "Yume Kojo Doki Doki Panic". Nintendo cheated US people by just replacing the main character to mario. See this video (https://www.youtube.com/watch?v=SWHShX0Imww).

**Comment by capnmidnight** [comment]
Oh good, the pedantic people made it.

**Comment by xem** [comment]
Anyway, on NES that's SMB2(U), even if they adapted another game to make it... Yume is (J) only, and the original SMB2(J) was only released in Japan. On GBA, these considerations make no sense. :p

**Comment by jsemu** [comment]
tfw a repo that was not really ready for people to see and was a code golf testing grounds gets trending and this happens.
