### ISSUE TITLE
Emulation goes smoothly when moving the mouse :S

### ISSUE THREAD

**Issue by allende** [jsemu/gba#5]
Hi I'm using the emulator in Chrome Version 43.0.2357.81 m
WebGL is disabled (Intel graphic card) but notice when moving the mouse randomly (just making circles) the game runs smoothly (better framerate), then if I'm not moving the mouse the frames got choppy

Don't if this an issue in the emulator or on my PC, will try in another PC (WebGL enable) and in a tablet and will let you know how it goes.

**Comment by jsemu** [comment]
This is not not how the emulator works. It's something with your PC or chrome. Also this runs 2x faster in Firefox.
