### ISSUE TITLE
How to save  my Progress

### ISSUE THREAD

**Issue by NickoZX** [jsemu/gba#6]
Maybe someone can tell me how to save my progress in the different games.
If this is cannot possible, maybe someone can do it something to make it possible.
Thanks for this project, I like it a lot

**Comment by Elmapul** [comment]
AFAIK its not yet avaliable, it probably can be done with local storage

**Comment by jsemu** [comment]
The code was already there, there was simply a typo that was overlooked.

Should be fixed in https://github.com/jsemu/gba/commit/9f18eafa1a2b975212fdc8639a2ea3e06a989d67
